server:
  port: 8080


spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: member-service
              uri: lb://member-service
              predicates:
                - Path=/api/members/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses/**
            - id: subscription-service
              uri: lb://subscription-service
              predicates:
                - Path=/api/subscriptions/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
