spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lxp-test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

auth:
  member-client:
    mode: ${AUTH_SERVICE_MEMBER_CLIENT_MODE:rest} # rest(기본, REST 호출) | grpc(gRPC 호출)
    grpc:
      host: ${AUTH_SERVICE_MEMBER_CLIENT_GRPC_HOST:member-service}
      port: ${AUTH_SERVICE_MEMBER_CLIENT_GRPC_PORT:9090}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ${LOG_DIR:../infrastructure/logs}/${spring.application.name}.log

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-milliseconds: 3600000
  refresh-token-validity-milliseconds: 864000000
