services:

  consul-1:
    image: hashicorp/consul:1.18
    container_name: lxp-consul-1
    command: agent -server -ui -node=consul-1 -bootstrap-expect=3 -client=0.0.0.0 -retry-join=consul-2 -retry-join=consul-3
    ports:
      - "8500:8500"
    networks: [lxp-net]
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 10

  consul-2:
    image: hashicorp/consul:1.18
    container_name: lxp-consul-2
    command: agent -server -node=consul-2 -bootstrap-expect=3 -client=0.0.0.0 -retry-join=consul-1 -retry-join=consul-3
    networks: [lxp-net]

  consul-3:
    image: hashicorp/consul:1.18
    container_name: lxp-consul-3
    command: agent -server -node=consul-3 -bootstrap-expect=3 -client=0.0.0.0 -retry-join=consul-1 -retry-join=consul-2
    networks: [lxp-net]


  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: lxp-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [lxp-net]

  grafana:
    image: grafana/grafana:11.4.0
    container_name: lxp-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks: [lxp-net]

  loki:
    image: grafana/loki:3.3.2
    container_name: lxp-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infrastructure/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks: [lxp-net]

  alloy:
    image: grafana/alloy:latest
    container_name: lxp-alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./infrastructure/logs:/var/log/lxp:ro
      - alloy-data:/var/lib/alloy/data
    ports:
      - "12345:12345"
    depends_on:
      - loki
    networks: [lxp-net]

  zipkin:
    image: openzipkin/zipkin:3.4
    container_name: lxp-zipkin
    ports:
      - "9411:9411"
    networks: [lxp-net]


networks:
  lxp-net:
    name: lxp-net
    driver: bridge

volumes:
  grafana-data:
  loki-data:
  alloy-data:
