plugins {
    id 'buildlogic.java-spring-boot-conventions'
    id 'buildlogic.java-spring-boot-observability-conventions'
    id 'buildlogic.java-spring-cloud-config-client-conventions'
    id 'buildlogic.java-spring-boot-web-conventions'
    id 'buildlogic.java-spring-boot-jpa-conventions'
}

group = 'com.lcs'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'
}

tasks.named('test') {
    useJUnitPlatform {
        excludeTags 'rabbitmq-integration'
    }
}
