plugins {
    id 'buildlogic.java-spring-boot-conventions'
    id 'buildlogic.java-spring-boot-observability-conventions'
    id 'buildlogic.java-spring-cloud-config-client-conventions'
}

group = 'com.lcs'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    runtimeOnly 'com.h2database:h2'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'
}

tasks.named('test') {
    useJUnitPlatform {
        excludeTags 'rabbitmq-integration'
    }
}
