plugins {
    id 'buildlogic.java-spring-boot-conventions'
    id 'buildlogic.java-spring-boot-observability-conventions'
    id 'buildlogic.java-spring-cloud-config-client-conventions'
    id 'buildlogic.java-spring-boot-web-conventions'
    id 'buildlogic.java-spring-boot-jpa-conventions'
    id 'buildlogic.java-spring-boot-aop-conventions'
    id 'buildlogic.java-spring-boot-amqp-conventions'
}

group = 'com.lcs'
version = '0.0.1-SNAPSHOT'

tasks.named('test') {
    useJUnitPlatform {
        excludeTags 'rabbitmq-integration'
    }
}
